version: '3.8'

services:

  fe-app:
    image: fe-payment
    restart: on-failure
    depends_on:
      - be-app
    ports:
      - "3000:3000"

  be-app:
    image: be-payment
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'payment'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'payment'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: